language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - buildozer android debug
  - ls
deploy:
  provider: releases
  api_key: "$GITHUB"
  file_glob: true
  file: "*.apk"
  skip_cleanup: true
  on:
    tags: true
