language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - git clone https://github.com/kivy/buildozer.git
  - cd buildozer
