android:
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - git clone https://github.com/kivy/buildozer.git
  - cd buildozer
  - python3 setup.py install
  - cd ..
  - buildozer init
  - buildozer android deploy
